# Generated by Django 2.1.7 on 2019-03-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('host', models.CharField(max_length=64)),
                ('source', models.CharField(max_length=16)),
                ('date', models.DateField()),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
